# compose.yaml

include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python

    # Всегда перезапускать при ошибке
    restart: on-failure

    # Та же сеть backend, что и в proxy.yaml
    networks:
      backend:
        ipv4_address: 172.20.0.5


    # Переменные из main.py:
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

    depends_on:
      - db

  db:
    image: mysql:8
    restart: on-failure

    networks:
      backend:
        ipv4_address: 172.20.0.10

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  db_data: